spring:
  application:
    name: eurekaserver
  security:
    basic:
      enable: true
    user:
      name: cursoms-eureka-user
      password: se-a-esmrreruoukusc

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

